/* A simple demonstration of using Pacta to compose asynchronous HTTP requests.
 *
 * When run, this program will output four random code names as generated by
 * Clive Murray's http://codenames.clivemurray.com.
 *
 * In this example, http.getJSON() returns a Promise of the parsed JSON from the
 * given URL. For these specific URLs, an array of objects will be returned (one
 * URL returns a list of "prefixes" and the other returns a list of animal
 * names).
 *
 * See examples/codenames-2.js for another way to achieve the same result.
 */
var http = require('./promised-http'),
    Promise = require('../lib/pacta');

var random = function (coll) {
    return coll[Math.floor(Math.random() * coll.length)];
};

var promisedPrefixes = http.getJSON('http://codenames.clivemurray.com/data/prefixes.json'),
    promisedAnimals = http.getJSON('http://codenames.clivemurray.com/data/animals.json'),
    prefixesAndAnimals = Promise.all([promisedPrefixes, promisedAnimals]);

var promisedCodeName = function () {
    return prefixesAndAnimals.spread(function (prefixes, animals) {
        var prefix = random(prefixes),
            animal = random(animals);

        return prefix.title + animal.title;
    });
};

promisedCodeName().map(console.log);
promisedCodeName().map(console.log);
promisedCodeName().map(console.log);
promisedCodeName().map(console.log);
